# To run it, do:
#   $ docker-compose pull && docker-compose up -d
#
# To upgrade, do:
#   $ docker-compose pull && docker-compose stop && docker-compose rm -f && docker-compose up -d
#
# To check the logs, do:
#   $ docker-compose logs -f
#

version: '2'

services:
  tomcat-server:
    image: tomcat

  shibboleth-sp:
    image: jefferyb/shibboleth
    container_name: shibboleth-sp
    environment:
      ####### APACHE SECTION #######
      - SERVICE_TO_PROTECT='tomcat-server'
      - SERVICE_PORT='8080'
      ####### SHIBBOLETH SECTION #######
      - HOSTNAME='example.com'
      - IDP_ENTITY_ID='https://samltest.id/saml/idp'
      - IDP_METADATA_URL='https://samltest.id/saml/idp'
      - SUPPORT_EMAIL='root@localhost'
      - SHIB_METADATA_BACKUP_URL='https://samltest.id/saml/idp'
      - SHIB_DOWNLOAD_METADATA='true'
    ports:
      - 80:80
      - 443:443
    restart: always
    links:
      - tomcat-server
    # volumes:
    #   - $(pwd)/ssl/shib-sp.crt:/etc/apache2/ssl/ssl.crt:ro
    #   - $(pwd)/ssl/shib-sp.key:/etc/apache2/ssl/ssl.key:ro
